[tool.poetry]
name = "robotpy-toolkit-7407"
version = "0.1.1"
description = ""
authors = ["Ethan Chapman <ethan.chapman0@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"
robotpy = {extras = ["commands2", "ctre", "rev"], version = "^2022.0.21"}
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
