[tool.poetry]
name = "robotpy-toolkit-7407"
version = "0.5.10"
description = "FRC Wired Boars Team 7407's Toolkit for usage with RobotPy"
authors = ["Sidharth Rao <sidharthmrao@gmail.com>", "Ethan Chapman <ethan.chapman0@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.10"
robotpy = {extras = ["commands2"], version = "^2022.4.8"}
pydantic = "^1.9.0"
robotpy-ctre = "^2022.1.1"
robotpy-rev = "^2022.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
